spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devs
    username: root
mybatis-plus:
  #mapper映射
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

