server:
  port: 8080
  servlet:
    #跟路径：localhost:端口号/context-path/uri
    context-path: /root


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devs
    username: root
    password: Liusiyuan1
  jpa:
    hibernate:
      # 自动建表
      ddl-auto: update
      #在控制台输出sql
    show-sql: true