server:
  port: 8080
  servlet:
    #跟路径：localhost:端口号/context-path/uri
    context-path: /root


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devs
    username: root
    password: Liusiyuan1
  jpa:
    hibernate:
      # 自动建表
      ddl-auto: update
      #在控制台输出sql
    show-sql: true

mybatis:
  #用来实例化mapper的接口,找有@Mapper的注解去实例化 （接口本身不能被实例化，需要有实现才能被实例化）,或在启动类上添加@MapperScan
#  type-aliases-package: com.lsy.springboot.mapper
  #对应的sql映射，必须要!  classpath指的是resource下的文件夹
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # todo 开启mybatis驼峰式命名规则自动转换 ??  不生效
    map-underscore-to-camel-case: false