#mybatisplus 多数据源dynamic
#Spring Boot 2.0 以上默认使用 com.zaxxer.hikari.HikariDataSource 数据源,可以 通过 spring.datasource.type 指定数据源
spring:
  datasource:
    #Spring Boot 2.0以上默认连接池hikari
    hikari:
      #池中维护的最小空闲连接数（minIdle<0或者minIdle>maxPoolSize,则被重置为maxPoolSize）
      minimum-idle: 4
      #池中最大连接数，包括闲置和使用中的连接。（如果maxPoolSize小于1，则会被重置。当minIdle<=0被重置为DEFAULT_POOL_SIZE则为10;如果minIdle>0则重置为minIdle的值）
      maximum-pool-size: 16
      #等待来自池的连接的最大毫秒数,如果小于250毫秒，则被重置回30秒
      connection-timeout: 10000
      #连接允许在池中闲置的最长时间（如果idleTimeout+1秒>maxLifetime 且 maxLifetime>0，则会被重置为0（代表永远不会退出）；如果idleTimeout!=0且小于10秒，则会被重置为10秒）
      idle-timeout: 10000
      connection-init-sql: set names utf8mb4
      #池中连接最长生命周期(如果不等于0且小于30秒则会被重置回30分钟)
      max-lifetime: 100000
    dynamic:
      # 设置默认的数据源或数据源组，默认值即为master
      primary: master
      # 严格匹配数据源，默认false，true未匹配到指定数据源时抛异常，false使用默认数据源
      strict: false
      datasource:
        master:
          driverClassName: com.mysql.cj.jdbc.Driver
          # 连接url常用参数：
          # useUnicode：是否使用编码集。
          # characterEncoding：utf8、gbk等，设置字符集编码类型。
          # zeroDateTimeBehavior：convertToNull，datetime的字段值全部为0时的处理方式。
          # useSSL：是否使用SSL协议。（true 可以连接高版本的数据库）
          # serverTimezone：时区。
          # autoReconnect：当数据库连接异常中断时，是否自动重新连接
          # autoReconnectForPools：是否使用针对数据库连接池的重连策略
          # failOverReadOnly：自动重连成功后，连接是否设置为只读
          url: jdbc:mysql://localhost:3306/devs?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
          username: root
          password: Liusiyuan1
        prod:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/prod?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
          username: root
          password: Liusiyuan1

