spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devs?autoReconnect=true
    username: root
    password: Liusiyuan1
mybatis-plus:
  #mapper映射
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

